### ISSUE TITLE
Boyut Hatası 

### ISSUE THREAD

**Issue by Feronial** [deeplearningturkiye/kapsul-agi-capsule-network#3]
İyi Çalışmalar.

Normal şartlarda kodu kendim alıp modifiye ettiğim halinde el yapımı bir veri kümesinde başarı ile çalıştırdım. Fakat Mnist içinde denemek istedim. Kodu tavsiye ettiğiniz şekillde çalıştırınca ; 

tensorflow.python.framework.errors_impl.InvalidArgumentError: Dimensions must be equal, but are 1152 and 16 for 'digitcaps/add_2' (op: 'AddV2') with input shapes: [?,10,?,1152], [?,10,10,1152,16,10,?,16].

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "capsulenet.py", line 206, in <module>
    num_routing=args.num_routing)
  File "capsulenet.py", line 44, in CapsNet
    name='digitcaps')(primarycaps)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/base_layer.py", line 451, in __call__
    output = self.call(inputs, **kwargs)
  File "/content/kapsul-agi-capsule-network/capsulelayers.py", line 167, in call
    b += K.batch_dot(outputs, inputs_hat_stopped, [2, 3])
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/ops/math_ops.py", line 899, in binary_op_wrapper
    return func(x, y, name=name)
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/ops/math_ops.py", line 1197, in _add_dispatch
    return gen_math_ops.add_v2(x, y, name=name)
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/ops/gen_math_ops.py", line 549, in add_v2
    "AddV2", x=x, y=y, name=name)
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/framework/ops.py", line 1770, in __init__
    control_input_ops)
  File "/tensorflow-1.15.0/python3.6/tensorflow_core/python/framework/ops.py", line 1610, in _create_c_op
    raise ValueError(str(e))
ValueError: Dimensions must be equal, but are 1152 and 16 for 'digitcaps/add_2' (op: 'AddV2') with input shapes: [?,10,?,1152], [?,10,10,1152,16,10,?,16].

Şu Hatayı aldım. Çözmeye uğraşacağım. Bilginize. Ellerinize sağlık

**Comment by Feronial** [comment]
Sorunu çözdüm. Keras versiyonu ile alakalıymış. 

**keras == 2.2.4
tensorflow == 1.15**

Şeklinde yapınca modeli oluşturdu.
